// unity.cpp
#define _USE_MATH_DEFINES
#include <math.h>
#define localtime_r(a, b) localtime_s(b, a)

#include "../logic/src/ARCodeFile.cpp"
#include "../logic/src/ARDatabaseDAT.cpp"
#include "../logic/src/AREngine.cpp"
#include "../logic/src/ARM.cpp"
#include "../logic/src/ARMInterpreter.cpp"
#include "../logic/src/ARMInterpreter_ALU.cpp"
#include "../logic/src/ARMInterpreter_Branch.cpp"
#include "../logic/src/ARMInterpreter_LoadStore.cpp"
#include "../logic/src/CP15.cpp"
#include "../logic/src/CRC32.cpp"
#include "../logic/src/DMA.cpp"
#include "../logic/src/DMA_Timings.cpp"
#include "../logic/src/DSi.cpp"
#include "../logic/src/DSi_AES.cpp"
#include "../logic/src/DSi_Camera.cpp"
#include "../logic/src/DSi_DSP.cpp"
#include "../logic/src/DSi_I2C.cpp"
#include "../logic/src/DSi_I2S.cpp"
#include "../logic/src/DSi_NAND.cpp"
#include "../logic/src/DSi_NDMA.cpp"
#include "../logic/src/DSi_NWifi.cpp"
#include "../logic/src/DSi_SD.cpp"
#include "../logic/src/DSi_SPI_TSC.cpp"
#include "../logic/src/FATIO.cpp"
#include "../logic/src/FATStorage.cpp"
#include "../logic/src/GBACart.cpp"
#include "../logic/src/GBACartMotionPak.cpp"
#include "../logic/src/GPU.cpp"
#include "../logic/src/GPU_Soft.cpp"
#include "../logic/src/GPU2D.cpp"
#include "../logic/src/GPU2D_Soft.cpp"
#include "../logic/src/GPU3D.cpp"
#include "../logic/src/GPU3D_Soft.cpp"
#include "../logic/src/GPU3D_Texcache.cpp"
#include "../logic/src/Mic.cpp"
#include "../logic/src/NDS.cpp"
#include "../logic/src/NDSCart.cpp"
#include "../logic/src/ROMList.cpp"
#include "../logic/src/FreeBIOS.cpp"
#include "../logic/src/RTC.cpp"
#include "../logic/src/Savestate.cpp"
#include "../logic/src/SPI.cpp"
#include "../logic/src/SPI_Firmware.cpp"
#include "../logic/src/SPU.cpp"
#include "../logic/src/Utils.cpp"
#include "../logic/src/Wifi.cpp"
#include "../logic/src/WifiAP.cpp"

#include "../logic/src/DSP_HLE/UcodeBase.cpp"
#include "../logic/src/DSP_HLE/AACUcode.cpp"
#include "../logic/src/DSP_HLE/G711Ucode.cpp"
#include "../logic/src/DSP_HLE/GraphicsUcode.cpp"

// CartCommon.cpp moved to unity2.cpp
#include "../logic/src/NDSCart/CartRetail.cpp"
#include "../logic/src/NDSCart/CartRetailNAND.cpp"
#include "../logic/src/NDSCart/CartRetailIR.cpp"
#include "../logic/src/NDSCart/CartRetailBT.cpp"
#include "../logic/src/NDSCart/CartSD.cpp"
#include "../logic/src/NDSCart/CartHomebrew.cpp"
#include "../logic/src/NDSCart/CartR4.cpp"

// Teakra (DSi DSP emulator)
#include "../logic/src/teakra/src/ahbm.cpp"
#include "../logic/src/teakra/src/apbp.cpp"
#include "../logic/src/teakra/src/btdmp.cpp"
#include "../logic/src/teakra/src/dma.cpp"
#include "../logic/src/teakra/src/memory_interface.cpp"
#include "../logic/src/teakra/src/mmio.cpp"
#include "../logic/src/teakra/src/processor.cpp"
#include "../logic/src/teakra/src/timer.cpp"
#include "../logic/src/teakra/src/teakra.cpp"
